### ISSUE TITLE
@argfile aka Response files

### ISSUE THREAD

**Issue by kastiglione** [Ubehebe/bazel-worker-examples#1]
Hi, thanks for writing this up. We went through some of the exact same issues with using Python to write a persistent worker. It's awesome that you've documented this all.

I wanted to add some info about the argfiles. They are hard to google, one name they go by is: "response files". Clang and most llvm tools support them (including Swift). The llvm command line API supports it as well: https://github.com/Ubehebe/bazel-worker-examples#argfile-convention. Also gcc supports them (its docs don't say response file, they show `@file`), as do many Microsoft tools.

**Comment by Ubehebe** [comment]
Thanks for the info! Glad I'm not the only one trying to get these things to work together.

If you/your company is working on Python/Bazel infrastructure, I might be interested in collaborating. The reason I dug into all this stuff was that I wanted a good development experience for ML and visualization tools. In particular, the Plotly Python library has a huge startup cost; doing those imports in a worker brought my edit-refresh latency for browser visualizations down to a couple seconds.

Anyway, there's a lot that can be improved.
